app:
  api:
    base-url: http://localhost:8080/api/
  navigation:
    history:
      max: 10
logging:
  file:
    name: logs/stud-sluzba-client.log
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"